server:
  port: 8080


spring:
  dataSource:
    url: jdbc:mysql://81.68.164.7:3306/gulimall?characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&useSSL=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: lss123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 300000
      connection-test-query: 'SELECT 1'

quartz:
  cronExpression: 0/5 * * * * ?



