spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  cloud:
    gateway:
      routes:
        - id: eden
          path: /test/**
          uri: http://localhost:8093
          predicates:
            - Path=/test/**

server:
  port: 9999

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: debug
